(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const c={form:document.querySelector("#task-form"),list:document.querySelector("#task-list"),taskName:document.querySelector('[name="taskName"]'),taskDescription:document.querySelector('[name="taskDescription"]')},u=(s,t)=>{localStorage.setItem(s,JSON.stringify(t))},d=s=>{const t=localStorage.getItem(s);return t?JSON.parse(t):null},a=s=>{const t=s.map(r=>`
    <li class="task-list-item">
    <button class="task-list-item-btn">
      Delete
    </button>
    <h3>${r.title}</h3>
    <p>${r.description}</p>
    </li>`).join("");c.list.innerHTML=t};let i=d("tasks")||[];const m=()=>{a(i)},f=s=>{i.push(s),a(i),u("tasks",i)},p=(s,t)=>{const r=i.filter(n=>n.title!==s&&n.description!==t);i=r,u("tasks",i),a(r)};m();c.form.addEventListener("submit",s=>{s.preventDefault();const t=c.taskName.value.trim(),r=c.taskDescription.value.trim(),n={};if(!t||!r){alert("Заповніть усі поля!");return}n.title=t,n.description=r,f(n),c.form.reset()});c.list.addEventListener("click",s=>{s.preventDefault();const t=s.target.nextElementSibling,r=t&&t.textContent||"",n=t?t.nextElementSibling:null,e=n&&n.textContent||"";p(r,e)});
//# sourceMappingURL=index.js.map
